# Generated by Django 5.2.4 on 2025-07-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_roshen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roshen',
            new_name='Meeting',
        ),
    ]
