# Generated by Django 5.2.4 on 2025-07-30 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_roshen_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='created_at',
            new_name='date_and_time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='dept',
            new_name='type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_taker',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
