# Generated by Django 5.2.4 on 2025-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meeting_minutes_taker_meeting_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
