# Generated by Django 5.2.4 on 2025-08-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date_and_time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='type',
        ),
        migrations.CreateModel(
            name='MeetingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('participant', 'Participant')], max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meeting')},
            },
        ),
    ]
